/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComerciosRouteImport } from './routes/comercios'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as SaudeRouteImport } from './routes/saude'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComerciosRoute = ComerciosRouteImport.update({
  id: '/comercios',
  path: '/comercios',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudeRoute = SaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comercios': typeof ComerciosRoute
  '/restaurantes': typeof RestaurantesRoute
  '/saude': typeof SaudeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comercios': typeof ComerciosRoute
  '/restaurantes': typeof RestaurantesRoute
  '/saude': typeof SaudeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comercios': typeof ComerciosRoute
  '/restaurantes': typeof RestaurantesRoute
  '/saude': typeof SaudeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comercios' | '/restaurantes' | '/saude'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comercios' | '/restaurantes' | '/saude'
  id: '__root__' | '/' | '/comercios' | '/restaurantes' | '/saude'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComerciosRoute: typeof ComerciosRoute
  RestaurantesRoute: typeof RestaurantesRoute
  SaudeRoute: typeof SaudeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercios': {
      id: '/comercios'
      path: '/comercios'
      fullPath: '/comercios'
      preLoaderRoute: typeof ComerciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saude': {
      id: '/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof SaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComerciosRoute: ComerciosRoute,
  RestaurantesRoute: RestaurantesRoute,
  SaudeRoute: SaudeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
